### ISSUE TITLE
Changing Time Capsule/AirPort country (apple-sku)

### ISSUE THREAD

**Issue by 1gr8dane** [x56/airpyrt-tools#3]
I have some instructions on how to change the value "apple-sku" in my Time Capsule using ssh, but I am stopped by not being allowed to communicate through port 22.
Can anyone tell me how I open ssh communications to my TC, or Airport Extreme?

**Comment by itsmepetrov** [comment]
Try this #1

**Comment by oscarmorrison** [comment]
@1gr8dane can you please share the instructions for to change country code
