### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Lozhki-net** [x56/airpyrt-tools#6]
![image](https://user-images.githubusercontent.com/84327444/118492386-291a8980-b74a-11eb-9614-fba6ddbd6ebd.jpeg)

**Comment by Lozhki-net** [comment]
Mac OS big sur 11.3

-python setup.py install

**Comment by dluschan** [comment]
I installed the package pycrypto manually (from repository https://github.com/pycrypto/pycrypto):
git clone git@github.com:pycrypto/pycrypto.git
cd pycrypto
python setup.py install
